- name: Setup PHPMyAdmin
  block:
    - name: pull a phpmyadmin docker image
      docker_image:
        name: phpmyadmin/phpmyadmin
        source: pull
           
    - name: Create PHPMyAdmin container
      docker_container:
        name: "{{ phpmyadmin.name }}"
        detach: true
        image: "phpmyadmin/phpmyadmin"
        state: started
        restart: yes
        recreate: yes
        links:
          - "{{ phpmyadmin.db_container_name }}:db"
        ports:
          - "{{ phpmyadmin.output_port }}:80"
          
    - name: Add phpmyadmin to start on boot
      cron:
        name: "PhpMyAdmin container"
        special_time: reboot
        job: "docker start {{ phpmyadmin.name }}"
  become: yes