- name: Setup PHPMyAdmin
  block:
    - name: pull a mysql docker image
      docker_image:
        name: mysql
        source: pull
    
    - name: Create mysql container
      docker_container:
        name: "mysql"
        detach: true
        image: "mysql:latest"
        state: started
        restart: yes
        ports:
          - "3306:3306"
        env:
          MYSQL_ROOT_PASSWORD: root

  become: yes